export const storeProducts = [
  {
    id: 1,
    category: "bongden",
    title: "DÂY OVAN MỀM VCTFK 2×4.0",
    img: "product-img/product-1.png",
    price: 176000,
    company: "CadiSun",
    info: "+ Ruột dẫn: Đồng ủ mềm trong môi trường khí trơ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    category: "bongden",
    title: "Bóng đèn Rạng Đông 2",
    img: "product-img/product-2.png",
    price: 160000,
    company: "SAMSUNG",
    info: "sản phẩm 2",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    category: "bongden",
    title: "Bóng đèn Rạng Đông 3",
    img: "product-img/product-3.png",
    price: 80000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    category: "ongluondaydiensino",
    title: "Dây điện nano 1",
    img: "product-img/product-4.png",
    price: 180000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    category: "ongluondaydiensino",
    title: "Dây điện nano 2",
    img: "product-img/product-5.png",
    price: 240000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    category: "ongluondaydiensino",
    title: "Dây điện nano 3",
    img: "product-img/product-6.png",
    price: 170000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    category: "daycapdiencadivi",
    title: "Dây điện mềm Cadivi bọc nhựa PVC VCmo 2×0,75 (2×24/0.2)-300/500V",
    img: "product-img/product-7.png",
    price: 687000,
    company: "Cadivi",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    category: "daycapdiencadivi",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    category: "daycapdiencadisun",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    category: "daycapdiencadisun",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    category: "thietbidienpanasonic",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    category: "thietbidienpanasonic",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    category: "daucoss",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    category: "daucoss",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    category: "daucoss",
    title: "Cáp quang 1",
    img: "product-img/product-8.png",
    price: 20000000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0,
  },
];
