export const storeProducts = [
  {
    id: 1,
    category: 'bongden',
    title: "Bóng đèn Rạng Đông 1",
    img: "img/product-1.png",
    price: 10000,
    company: "GOOGLE",
    info: "sản phẩm 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    category: 'bongden',
    title: "Bóng đèn Rạng Đông 2",
    img: "img/product-2.png",
    price: 16000,
    company: "SAMSUNG",
    info: "sản phẩm 2",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    category: 'bongden',
    title: "Bóng đèn Rạng Đông 3",
    img: "img/product-3.png",
    price: 8000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    category: 'ongnuoc',
    title: "Dây điện nano 1",
    img: "img/product-4.png",
    price: 18000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    category: 'ongnuoc',
    title: "Dây điện nano 2",
    img: "img/product-5.png",
    price: 24000,
    company: "htc",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    category: 'ongnuoc',
    title: "Dây điện nano 3",
    img: "img/product-6.png",
    price: 17000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    category: 'daydien',
    title: "Iphone 7",
    img: "img/product-7.png",
    price: 30000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    category: 'daydien',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    category: 'daydien',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 12,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 13,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 14,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 15,
    category: 'capquang',
    title: "Cáp quang 1",
    img: "img/product-8.png",
    price: 2000,
    company: "apple",
    info: "Miêu tả bóng đèn 1",
    inCart: false,
    count: 0,
    total: 0
  },
];


