export const storeProducts = [
  {
    id: 1,
    category: "bongden",
    title: "BÓNG ĐÈN LED BULB (Model: LED A60N1/9W)",
    img: "/product-img/bong-den-led-blub.jpg",
    price: 70000,
    company: "Rạng Đông",
    info: "Công suất: 9W \n Điện áp: 220V/50Hz \n Nhiệt độ màu: 6500K/5000K/3000K \n Quang thông: 830 lm \n Kích thước (ØxH): 60 x 114 (mm) \n Sử dụng Chip LED có độ tin cậy cao \n Chất lượng ánh sáng cao (CRI> 80) tăng khả năng nhận diện màu sắc của vật. \n Dải điện áp rộng 150 – 250V đáp ứng dải điện áp lưới tại Việt Nam. \n Vỏ nhôm bọc nhựa chống lão hóa, Chống va đập",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    category: "bongden",
    title: "BÓNG ĐÈN LED BULB (Model: LED A70N1/12W)",
    img: "/product-img/bong-den-led-blub.jpg",
    price: 93000,
    company: "Rạng Đông",
    info: "Công suất: 12W \n Điện áp: 220V/50Hz \n Quang thông: 1080lm \n Màu ánh sáng: 6500K/5000K/3000K \n Đầu đèn: E27 \n Kích thước (ØxH): (70×135)mm \n Sử dụng Chip LED Samsung đạt độ tin cậy cao \n Chất lượng ánh sáng cao (CRI> 80) tăng khả năng nhận diện màu sắc của vật. \n Dải điện áp rộng 150 – 250V đáp ứng dải điện áp lưới tại Việt Nam. \n Vỏ nhôm bọc nhựa chống lão hóa, Chống va đập.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE NHÔM T8 MPE 6 TẤC (0,6M)10W",
    img: "/product-img/bong-den-led-tube.jpg",
    price: 213000,
    company: "MPE",
    info: "Quang thông: 950 lm \n Nhiệt độ màu (CCT): 6000-6500K/ 2800-3200K. Ánh sáng trắng, vàng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực\n Góc chiếu: 160°\n MPE Led Tube Aluminum T8 size: 588mm x 603mm x Ø26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE NHÔM T8 MPE 1M2",
    img: "/product-img/bong-den-led-tube.jpg",
    price: 254000,
    company: "MPE",
    info: "Quang thông: 1.850 lm \n Nhiệt độ màu (CCT): 6000-6500K/2800-3200K. Ánh sáng trắng, vàng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Góc chiếu: 160° \n MPE Led Tube Aluminum T8 size: 1197mm x 1213mm x Ø26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE THỦY TINH MPE 6 TẤC",
    img: "/product-img/bong-den-led-tube-thuy-tinh.jpg",
    price: 82400,
    company: "MPE",
    info: "Công suất: 9W \n Nhiệt độ màu: 6000-6500K/2800-3200K. Ánh sáng trắng, vàng tương ứng với 2 mã hàng: GT-60T, GT-60V có cùng mức giá 82.400 đồng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Quang thông: 1000 lm \n Điện áp: 175-265VAC \n Tiêu chuẩn châu Âu CE  ROHS \n RA>80 Chỉ số hoàn màu cao, ánh sáng trung thực \n Hệ số công suất (PF): >0.5 \n Tuổi thọ bóng: 30.000 giờ \n Chip LED: SMD2835 \n Góc chiếu: 330° \n Instant Light 0s 100% Sáng tức thì khi mở \n MPE LED Tube GT series size: 600mm x 26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE THỦY TINH MPE 1M2",
    img: "/product-img/bong-den-led-tube-thuy-tinh.jpg",
    price: 113700,
    company: "MPE",
    info: "Công suất: 18W \n Nhiệt độ màu: 6000-6500K/2800-3200K. Ánh sáng trắng, vàng tương ứng với 2 mã hàng: GT-120T, GT-120V có cùng mức giá 113.7000 đồng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Quang thông: 2000 lm \n Điện áp: 175-265VAC \n Tiêu chuẩn châu Âu CE  ROHS \n RA>80 Chỉ số hoàn màu cao, ánh sáng trung thực \n Hệ số công suất (PF): >0.5 \n Tuổi thọ bóng: 30.000 giờ \n Chip LED: SMD2835 \n Góc chiếu: 330° \n Instant Light 0s 100% Sáng tức thì khi mở \n MPE LED Tube GT series size: 1200mm x 26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE THỦY TINH T2 MPE 1M2",
    img: "/product-img/bong-den-led-tube-thuy-tinh-t2-mpe.png",
    price: 120000,
    company: "MPE",
    info: "Công suất: 20W \n Nhiệt độ màu: 6000-6500K/2800-3200K. Ánh sáng trắng, vàng tương ứng với 2 mã hàng: GT2-120T, GT2-120V có cùng mức giá 120.000 đồng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Quang thông: 2.500 lm \n Điện áp: 175-265VAC \n Tiêu chuẩn châu Âu CE  ROHS \n RA>80 Chỉ số hoàn màu cao, ánh sáng trung thực \n Hệ số công suất (PF): >0.5 \n Tuổi thọ bóng: 30.000 giờ \n Chip LED: SMD2835 \n Góc chiếu: 330° \n Instant Light 0s 100% Sáng tức thì khi mở \n Kích thước: 1200mm x 26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE THỦY TINH T3 MPE 1M2",
    img: "/product-img/bong-den-led-tube-thuy-tinh-t2-mpe.png",
    price: 130000,
    company: "MPE",
    info: "Công suất: 28W \n Nhiệt độ màu: 6000-6500K/2800-3200K. Ánh sáng trắng, vàng tương ứng với 2 mã hàng: GT3-120T, GT3-120V có cùng mức giá 130.000 đồng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Quang thông: 3.000 lm \n Điện áp: 175-265VAC \n Tiêu chuẩn châu Âu CE  ROHS \n RA>80 Chỉ số hoàn màu cao, ánh sáng trung thực \n Hệ số công suất (PF): >0.5 \n Tuổi thọ bóng: 30.000 giờ \n Chip LED: SMD2835 \n Góc chiếu: 330° \n Instant Light 0s 100% Sáng tức thì khi mở \n Kích thước: 1200mm x 26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    category: "bongden",
    title: "BÓNG ĐÈN LED TUBE THỦY TINH T5 MPE 1M2",
    img: "/product-img/bong-den-led-tube-thuy-tinh-t2-mpe.png",
    price: 125000,
    company: "MPE",
    info: "Công suất: 22W \n Nhiệt độ màu: 6000-6500K/2800-3200K. Ánh sáng trắng, vàng tương ứng với 2 mã hàng: GT5-120T, GT5-120V có cùng mức giá 125.000 đồng \n Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Quang thông: 2.600 lm \n Điện áp: 175-265VAC \n Tiêu chuẩn châu Âu CE  ROHS \n RA>80 Chỉ số hoàn màu cao, ánh sáng trung thực \n Hệ số công suất (PF): >0.5 \n Tuổi thọ bóng: 30.000 giờ \n Chip LED: SMD2835 \n Góc chiếu: 330° \n Instant Light 0s 100% Sáng tức thì khi mở \n Kích thước: 1200mm x 26mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    category: "bongden",
    title: "BỘ ĐÈN LED TUBE THỦY TINH BÓNG ĐÔI MPE 60CM",
    img: "/product-img/bo-den-led-thuy-tinh-bong-doi.jpg",
    price: 236000,
    company: "MPE",
    info: "Công suất: 9w \n Theo tiêu chuẩn châu Âu \n – CE RoHS \n – Điện áp: 100-240VAC \n – Tuổi thọ: 30 000 giờ \n – Chip LED: SMD2835 \n – RA>80 PF>0.9 \n – Instant Light 0s",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    category: "bongden",
    title: "BỘ ĐÈN LED TUBE THỦY TINH BÓNG ĐÔI MPE 1M2",
    img: "/product-img/bo-den-led-thuy-tinh-bong-doi.jpg",
    price: 287000,
    company: "MPE",
    info: "Công suất: 18w \n Theo tiêu chuẩn châu Âu \n – CE RoHS \n – Điện áp: 100-240VAC \n – Tuổi thọ: 30 000 giờ \n – Chip LED: SMD2835 \n – RA>80 PF>0.9 \n – Instant Light 0s",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    category: "bongden",
    title: "BỘ ĐÈN LED TUBE THỦY TINH T8 BÓNG ĐÔI MPE 60CM",
    img: "/product-img/bo-den-led-thuy-tinh-bong-doi.jpg",
    price: 236400,
    company: "MPE",
    info: "Công suất: 9w \n Theo tiêu chuẩn châu Âu \n – CE RoHS \n – Điện áp: 100-240VAC \n – Tuổi thọ: 30 000 giờ \n – Chip LED: SMD2835 \n – RA>80 PF>0.9 \n – Instant Light 0s",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    category: "bongden",
    title: "ĐÈN LED BULB 20W MPE LBD-20",
    img: "/product-img/bong-den-led-bulb-50w.jpg",
    price: 130000,
    company: "MPE",
    info: "Quang thông: 2.000 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 2800-3200K/6000-6500K. Ánh sáng vàng, trắng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 176-265VAC \n Đui đèn: E27 \n Trọng lượng: 106g \n Chip LED: SMD2835 \n RA >80     Chỉ số hoàn màu cao \n Hệ số công suất (PF):  >0.5 \n Instant Light: 0s \n Led Bulb MPE LBD-20W size: Ø80mm x 152mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    category: "bongden",
    title: "ĐÈN LED BULB 30W MPE LBD-30",
    img: "/product-img/bong-den-led-bulb-50w.jpg",
    price: 193000,
    company: "MPE",
    info: "Quang thông: 3.000 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 2800-3200K/6000-6500K. Ánh sáng vàng, trắng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 176-265VAC \n Đui đèn: E27 \n Trọng lượng: 166g \n Chip LED: SMD2835 \n RA >80     Chỉ số hoàn màu cao \n Hệ số công suất (PF):  >0.5 \n Instant Light: 0s \n Led Bulb MPE LBD-30W size: Ø100mm x 180mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    category: "bongden",
    title: "ĐÈN LED BULB 40W MPE LBD-40",
    img: "/product-img/bong-den-led-bulb-50w.jpg",
    price: 273000,
    company: "MPE",
    info: "Quang thông: 4.000 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 2800-3200K/6000-6500K. Ánh sáng vàng, trắng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 176-265VAC \n Đui đèn: E27 \n Trọng lượng: 166g \n Chip LED: SMD2835 \n RA >80     Chỉ số hoàn màu cao \n Hệ số công suất (PF):  >0.5 \n Instant Light: 0s \n Led Bulb MPE LBD-40W size: Ø118mm x 216mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    category: "bongden",
    title: "ĐÈN LED BULB 50W MPE LBD-50",
    img: "/product-img/bong-den-led-bulb-50w.jpg",
    price: 389000,
    company: "MPE",
    info: "Quang thông: 5.000 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 2800-3200K/6000-6500K. Ánh sáng vàng, trắng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 176-265VAC \n Đui đèn: E27 \n Trọng lượng: 240g \n Chip LED: SMD2835 \n RA >80 Chỉ số hoàn màu cao \n Hệ số công suất (PF): >0.5 \n Instant Light: 0s \n Led Bulb MPE LBD-50W size: Ø138mm x 245mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    category: "bongden",
    title: "ĐÈN LED BULB 15W MPE LBD2-15",
    img: "/product-img/bong-den-led-bulb-lbd2.jpg",
    price: 112000,
    company: "MPE",
    info: "Quang thông: 1.500 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 6000-6500K/2800-3200K. Ánh sáng trắng, vàng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 100-265VAC \n Đui đèn: E27 \n Chip LED: SMD2835 \n RA >80 Chỉ số hoàn màu cao \n Hệ số công suất (PF):  >0.5 \n Instant Light: 0s \n Kích thước: Ø65mm x 130mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    category: "bongden",
    title: "ĐÈN LED BULB 20W MPE LBD2-20",
    img: "/product-img/bong-den-led-bulb-lbd2.jpg",
    price: 129000,
    company: "MPE",
    info: "Quang thông: 2.000 lm \n Tuổi thọ bóng: 30.000 giờ \n Nhiệt độ màu (CCT): 6000-6500K/2800-3200K. Ánh sáng trắng, vàng. Ánh sáng liên tục, tốt cho thị lực \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 100-265VAC \n Đui đèn: E27 \n Chip LED: SMD2835 \n RA >80 Chỉ số hoàn màu cao \n Hệ số công suất (PF):  >0.5 \n Instant Light: 0s \n MPE Led Bulb LBD2-20W size: Ø80mm x 152mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    category: "bongden",
    title: "ĐÈN LED BULB CHỐNG MUỖI LB-9T/AM",
    img: "/product-img/bulb-chong-muoi.jpg",
    price: 174000,
    company: "MPE",
    info: "Quang thông: 806 lm \n 2 chế độ sáng: chế độ chống muỗi và chế độ đèn sáng trắng \n Nhiệt độ màu (CCT): 6500K/3500K. Ánh sáng trắng, vàng chanh. Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n Phạm vi hoạt động: 10-12 m² \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 100-240VAC \n Tuổi thọ bóng: 30.000 giờ \n Trọng lượng: 67g \n Frequency: 50Hz \n RA>80 Chỉ số hoàn màu cao \n Hệ số công suất (PF): >0.5 \n Instant Light: 0s \n MPE Led Bulb Anti Mosquito size: Ø60mm x 120mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    category: "bongden",
    title: "LED BULB CẢM BIẾN CHUYỂN ĐỘNG LB-9T/MS",
    img: "/product-img/bulb-chong-muoi.jpg",
    price: 291000,
    company: "MPE",
    info: "Quang thông: 850 lm \n Nhiệt độ màu (CCT): 6000-6500K. Ánh sáng trắng. Ánh sáng liên tục, không nhấp nháy, tốt cho thị lực \n 2 chức năng: phát hiện chuyển động và đo độ sáng \n Thông minh và tiết kiệm năng lượng – làm việc trong điều kiện ánh sáng yếu, sáng lên khi bạn đến gần và trì hoãn tắt khi bạn rời đi. \n Vùng cảm biến được mở rộng, góc quét rộng hơn \n Tiêu chuẩn châu Âu CE – RoHS \n Điện áp: 100-240VAC \n Tuổi thọ bóng: 30.000 giờ \n Trọng lượng: 78g \n Frequency: 50Hz \n RA>80 Chỉ số hoàn màu cao \n Hệ số công suất (PF): >0.5 \n Instant Light: 35s \n MPE Led Bulb Motion Sensor size: Ø70mm x 120mm",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 21,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9016",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 20000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	16 \n Độ dày (mm) :	1.40 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 22,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9020",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 28000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	20 \n Độ dày (mm) :	1.55 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9025",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 40500,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	25 \n Độ dày (mm) :	1.70 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 24,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9032",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 80000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	32 \n Độ dày (mm) :	2.10 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 25,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9040",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 111000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	40 \n Độ dày (mm) :	2.30 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 26,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9050",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 148000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	50 \n Độ dày (mm) :	2.60 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 27,
    category: "ongluondaydiensino",
    title: "Ống luồn dây điện 750N – SP9063",
    img: "/product-img/ong-luon-day-dien-sino.png",
    price: 178000,
    company: "SP",
    info: "Loại :	Ống nhựa cứng \n Đường kính ngoài (mm) :	63 \n Độ dày (mm) :	3.00 \n Chất liệu :	Nhựa \n Xuất xứ :	Việt Nam",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 28,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 1 đường loại thấp – Model E240/16/1",
    img: "/product-img/hop-chia-nga-1.jpg",
    price: 6300,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 1 đường loại thấp Ø 16mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 29,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 2 đường loại thấp – Model E240/16/2",
    img: "/product-img/hop-chia-nga-2.jpg",
    price: 6800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 2 đường loại thấp Ø 16mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 30,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 2 đường vuông góc loại thấp – Model E240/16/2A",
    img: "/product-img/hop-chia-nga-2-vuong-goc.jpg",
    price: 6800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 2 đường vuông góc loại thấp Ø 16mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 31,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 3 đường loại thấp – Model E240/16/3",
    img: "/product-img/hop-chia-nga-3.jpg",
    price: 6800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 3 loại thấp Ø 16mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 32,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 4 đường loại thấp – Model E240/16/4",
    img: "/product-img/hop-chia-nga-4.jpg",
    price: 6800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 4 loại thấp Ø 16mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 33,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 1 đường loại thấp – Model E240/25/1",
    img: "/product-img/hop-chia-nga-1.jpg",
    price: 7800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 1 loại thấp Ø 25mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 34,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 2 đường vuông góc loại thấp – Model E240/25/2A",
    img: "/product-img/hop-chia-nga-2-vuong-goc.jpg",
    price: 7800,
    company: "Sino",
    info: "– Hộp chia ngả (Sino) 2 vuông góc loại thấp Ø 25mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 3 đường loại thấp – Model E240/25/1",
    img: "/product-img/hop-chia-nga-3.jpg",
    price: 7800,
    company: "SP",
    info: "– Hộp chia ngả (Sino) 3 loại thấp Ø 25mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 36,
    category: "ongluondaydiensino",
    title: "Hộp chia ngả (Sino) 4 đường loại thấp – Model E240/25/1",
    img: "/product-img/hop-chia-nga-4.jpg",
    price: 7800,
    company: "SP",
    info: "– Hộp chia ngả (Sino) 4 loại thấp Ø 25mm. \n – Được sản xuất bằng nhựa PVC cao cấp được sản xuất theo dây chuyền tiêu chuẩn BS6099. \n – Là giải pháp được sử dụng rất nhiều tại các công trình thích hợp cho việc lắp trên trần, chìm trong tường hoặc chôn dưới đất. \n – Có khả năng chịu lực, chịu nén, chống cháy và bền bỉ trong khoảng nhiệt độ từ -15 đến 60 độ C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    category: "daycapdiencadivi",
    title: "Cáp điện lực hạ thế Cadivi CVV 2×1,5 – 300/500V",
    img: "/product-img/cap-dien-luc-ha-the-cadivi.jpg",
    price: 17800,
    company: "Cadivi",
    info: "– Cấp điện áp U0/U: 300/500V. \n – Điện áp thử: 2kV (5 phút). \n – Nhiệt độ làm việc dài hạn cho phép của ruột dẫn là 70°C. \n – Nhiệt độ cực đại cho phép của ruột dẫn khi ngắn mạch trong thời gian không quá 5 giây là 160°C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 38,
    category: "daycapdiencadivi",
    title: "Cáp điện lực hạ thế Cadivi CVV 2×2,5 – 300/500V",
    img: "/product-img/cap-dien-luc-ha-the-cadivi.jpg",
    price: 26000,
    company: "Cadivi",
    info: "– Cấp điện áp U0/U: 300/500V. \n – Điện áp thử: 2kV (5 phút). \n – Nhiệt độ làm việc dài hạn cho phép của ruột dẫn là 70°C. \n – Nhiệt độ cực đại cho phép của ruột dẫn khi ngắn mạch trong thời gian không quá 5 giây là 160°C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 39,
    category: "daycapdiencadivi",
    title: "Cáp điện lực hạ thế Cadivi CVV 2×4 – 300/500V",
    img: "/product-img/cap-dien-luc-ha-the-cadivi.jpg",
    price: 37800,
    company: "Cadivi",
    info: "– Cấp điện áp U0/U: 300/500V. \n – Điện áp thử: 2kV (5 phút). \n – Nhiệt độ làm việc dài hạn cho phép của ruột dẫn là 70°C. \n – Nhiệt độ cực đại cho phép của ruột dẫn khi ngắn mạch trong thời gian không quá 5 giây là 160°C.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 40,
    category: "daycapdiencadivi",
    title: "Cáp điện lực hạ thế Cadivi CVV 2×6 – 300/500V",
    img: "/product-img/cap-dien-luc-ha-the-cadivi.jpg",
    price: 52200,
    company: "Cadivi",
    info: "– Cấp điện áp U0/U: 300/500V. \n – Điện áp thử: 2kV (5 phút). \n – Nhiệt độ làm việc dài hạn cho phép của ruột dẫn là 70°C. \n – Nhiệt độ cực đại cho phép của ruột dẫn khi ngắn mạch trong thời gian không quá 5 giây là 160°C.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
